Update bestdns.yaml

diff --git a/.github/workflows/bestdns.yaml b/.github/workflows/bestdns.yaml
--- a/.github/workflows/bestdns.yaml
+++ b/.github/workflows/bestdns.yaml
@@ -71,11 +71,13 @@ jobs:
           keep_minimum_runs: 10  # 保留最近的 10 次工作流记录
           baseUrl: https://api.github.com
           repository: dxs1256/Best-DNS
-          dry_run: true  # 启用 dry_run，首先检查删除情况
+          dry_run: false  # <-- 修改为 false
+        if: success() #确保只有在前面步骤成功后才执行删除操作
 
-      # 启用调试模式
-      - name: Enable Debug Mode for Delete Workflow Runs
+
+      - name: Check Delete Workflow Runs Result
+        if: steps.DeleteWorkflowRuns.conclusion == 'failure'
         run: |
-          echo "DEBUG mode enabled"
-        env:
-          DEBUG: true  # 启用调试模式来查看更多日志
+          echo "Error deleting workflow runs: ${{ steps.DeleteWorkflowRuns.conclusion }}"
+          echo "Error message: ${{ steps.DeleteWorkflowRuns.output }}"
+          exit 1 # 终止工作流
